# Generated by Django 5.2.15 on 2026-07-04 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FareSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_minute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rounding_step', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fare_settings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='pricing_single_active_fare_setting')],
            },
        ),
    ]
