# Generated by Django 5.2.15 on 2026-07-05 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='faresetting',
            name='pricing_single_active_fare_setting',
        ),
        migrations.AddField(
            model_name='faresetting',
            name='vehicle_category',
            field=models.CharField(choices=[('KEKE', 'Keke (tricycle)'), ('CAR', 'Car')], db_index=True, default='CAR', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='faresetting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle_category',), name='pricing_single_active_fare_per_category'),
        ),
    ]
