# Generated by Django 5.2.15 on 2026-07-05 20:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of fare'), ('FIXED', 'Fixed amount per ride')], max_length=16)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage of fare'), ('FIXED', 'Fixed amount per ride')], default='', max_length=16)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending remittance'), ('REMITTED', 'Remitted'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=16)),
                ('remitted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_commissions', to='commissions.platformcommissionsetting')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_confirmed', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_commissions', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='rides.ride')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformcommissionsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='commissions_single_active_setting'),
        ),
        migrations.AddIndex(
            model_name='ridecommission',
            index=models.Index(fields=['driver', 'status'], name='commissions_driver__172a0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridecommission',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='commissions_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridecommission',
            constraint=models.CheckConstraint(condition=models.Q(('driver_earning__gte', 0)), name='commissions_earning_not_negative'),
        ),
    ]
