# Generated by Django 5.2.15 on 2026-07-22 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default="IJ Ride is down for scheduled maintenance. We'll be back shortly — thank you for your patience.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'maintenance mode',
                'verbose_name_plural': 'maintenance mode',
            },
        ),
    ]
