# Generated by Django 5.2.15 on 2026-07-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching for driver'), ('ACCEPTED', 'Accepted'), ('DRIVER_ARRIVED', 'Driver arrived'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='SEARCHING', max_length=16)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estimated_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank transfer')], default='CASH', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_role', models.CharField(blank=True, choices=[('PASSENGER', 'Passenger'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='', max_length=16)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_cancelled', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('fare_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='pricing.faresetting')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='drivers.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUESTED', 'Ride requested'), ('ACCEPTED', 'Driver accepted'), ('REJECTED', 'Driver rejected'), ('DRIVER_ARRIVED', 'Driver arrived'), ('TRIP_STARTED', 'Trip started'), ('TRIP_COMPLETED', 'Trip completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PAYMENT_CLAIMED', 'Payment claimed'), ('PAYMENT_CONFIRMED', 'Payment confirmed')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_events', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rides.ride')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', '-created_at'], name='rides_ride_passeng_c45f16_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', '-created_at'], name='rides_ride_driver__2fafcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SEARCHING', 'ACCEPTED', 'DRIVER_ARRIVED', 'IN_PROGRESS'])), fields=('passenger',), name='rides_one_active_ride_per_passenger'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('driver__isnull', False), ('status__in', ['ACCEPTED', 'DRIVER_ARRIVED', 'IN_PROGRESS'])), fields=('driver',), name='rides_one_active_ride_per_driver'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['ride', 'created_at'], name='rides_ridee_ride_id_277de8_idx'),
        ),
    ]
