# Generated by Django 5.2.15 on 2026-07-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='requested_vehicle_category',
            field=models.CharField(choices=[('KEKE', 'Keke (tricycle)'), ('CAR', 'Car')], db_index=True, default='CAR', max_length=16),
        ),
    ]
