# Generated by Django 5.2.15 on 2026-07-06 06:21

from django.db import migrations, models


def sync_from_active_vehicle(apps, schema_editor):
    """Existing drivers keep operating in the category their active vehicle
    belongs to. Drivers with no vehicle stay on the CAR default from the
    AddField step above."""
    DriverProfile = apps.get_model("drivers", "DriverProfile")
    for profile in DriverProfile.objects.all():
        vehicle = profile.vehicles.filter(is_active=True).first()
        if vehicle and vehicle.category != profile.driver_category:
            profile.driver_category = vehicle.category
            profile.save(update_fields=["driver_category"])


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_vehicle_category_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_category',
            field=models.CharField(choices=[('KEKE', 'Keke (tricycle)'), ('CAR', 'Car')], db_index=True, default='CAR', max_length=16),
        ),
        migrations.RunPython(sync_from_active_vehicle, migrations.RunPython.noop),
    ]
