# Generated by Django 5.2.15 on 2026-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_driver_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
