# Generated by Django 5.2.15 on 2026-07-16 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotp'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator(message='NIN must be exactly 11 digits.', regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('nin', ''), _negated=True), fields=('nin',), name='accounts_user_unique_nin_when_set'),
        ),
    ]
